### ISSUE TITLE
Implement multi-frequency fit

### ISSUE THREAD

**Issue by tcassanelli** [astronomy-laboratory/pyoof#2]
This is the particular case when given a set of OOF holography maps, another set is also recorded but at a different centred frequency, extra information that we may be able to use to constraint the fit.
A multi-frequency fit will, most certainly, increase the computation time.

I think this is a good time to explore a proper normalization of the power pattern, something that should, in principle, include the noise level. I believe that one of the two (or more frequencies) will have a higher noise level that should be tone down before combining it in a multi-fit nonlinear least-squares minimization.

**Comment by VicentePenaLet** [comment]
I was able to make the multifrequency fit work, I made modified function in order for the simulation to accept a list of frequencies, and modified the data extraction and data plotting in order to be consistent with the changes. I also modified the data extraction function so they return a dictionary instead of list so the data flow is easier to follow. There is an example notebook of the multifrequency fit in my development repo. I still have to fix some issues regarding the saving of plots, and I have to make sure I didn't break the normal fit function in the process.

The example can be found here, I used 3 wave lengths close to the original wave length of 9, the algorithm is able to plot all 3 of the original wavelengths with the estimated Zernike model.

https://github.com/VicentePenaLet/pyoofDevelopment/blob/master/notebooks/multifrequency_fit.ipynb

Currently my solution expect all wavelengths to have the same defocus, next step is to extend it so we can give a different defocus to each of the wavelengths. this relates to #3

**Comment by tcassanelli** [comment]
@VicentePenaLet great job!
A couple thoughts here:
- I'd rather for you to update code in a branch within [this repository](https://github.com/astronomy-laboratory/pyoof) so we can directly point code within issues and project board
- I'd rather for you to update the code, link it in the issue, and paste here the figures. Let's try not to use Jupyter notebooks within GitHub since they fill all the space with unnecessary MBs
- This is odd, but why does the computed phase doesn't look at all like the original one? The should be very similar in a simulation!
- After that phase plot is solved you need to start adding gaussian noise
- Different defocus $d_z$ and different $\lambda$ is an uncommon case, I think, but you can extend it if you want to

I would focus first in the different wavelength, make it work and study properly the result, i.e., check with noise, what is the tolerance, review the correlation between parameters. Another test would be to give many more $\lambda$ when does the problem become super constraint? There are many more things to test first with multiple $\lambda$.

**Comment by VicentePenaLet** [comment]
Ok, I will commit to this repository then.

in the notebook I'm just plotting the beam corresponding to the 15 um, here is a clearer comparison, the simulated beam is shown on top and the result from the model is shown below. 

<img width="818" alt="download (1)" src="https://user-images.githubusercontent.com/39199270/231191529-0691e937-436e-4d16-8b97-0163f4f89dc9.png">

<img width="818" alt="download" src="https://user-images.githubusercontent.com/39199270/231191550-63b68a03-13b7-40f5-8c44-a77ed5415b3e.png">

The phase errors in the notebook, are not the correct ones, I still need to tweak the phase error plotting function a bit, so ignore them for now.

**Comment by tcassanelli** [comment]
Some things that you can try:
- [ ] - [ ] Check phase plot residuals, what is the amplitud in comparison with a single frequency fit?
- [ ] Check correlation of parameters, does it reduce while including more frequencies?
- [ ] Include noise in the fit, does it perform better than a single frequency?

**Comment by VicentePenaLet** [comment]
I ran test using different frequencies, then plotted the correlation matrix 

wavelength = 9 um
![corr_n5_0 009000000000000001](https://user-images.githubusercontent.com/39199270/236941052-0298a336-28f5-4021-8b38-d3da13a0cca4.png) 

wavelength = 7, 9 um
![corr_n5_0 009000000000000001](https://user-images.githubusercontent.com/39199270/236941752-d56d1491-80f3-4118-8471-269a6ac3cee7.png)

wavelength = 7, 9, 11 um
![corr_n5_0 009000000000000001](https://user-images.githubusercontent.com/39199270/236941908-288c00d5-1f50-4078-80c3-77091f6ce4ed.png)

Visually it seems like the correlations are generally lower when we add more wavelengths.

**Comment by tcassanelli** [comment]
ah right, ok I see that it has decreased a bit, but I was expecting to give a better constraint since we're using way more data ... my questions would be now how do we properly normalize different data sets with different wavelengths.

**Comment by tcassanelli** [comment]
@VicentePenaLet can you plot the two phases and the residual difference?

**Comment by VicentePenaLet** [comment]
This is the original Simulated Phase Map
<img width="407" alt="download" src="https://github.com/astronomy-laboratory/pyoof/assets/39199270/8e3d0225-079f-4b90-af97-7cb9806c3be5">
This are the Phase map and phase error for simulated observation with a single 9 um wavelength
![fitphase_n5_0 009000000000000001](https://github.com/astronomy-laboratory/pyoof/assets/39199270/054d23a6-fb84-4533-9b4d-13e2957349f0)

<img width="407" alt="9" src="https://github.com/astronomy-laboratory/pyoof/assets/39199270/9450e7ef-8d38-4373-9d5c-2a1a7a260673">
This are the Phase map and phase error for simulated observation with a 7 and 9 um wavelength

![fitphase_n5_0 009000000000000001](https://github.com/astronomy-laboratory/pyoof/assets/39199270/a4e65481-4355-433d-b948-b34d0cb75e23)
<img width="400" alt="79" src="https://github.com/astronomy-laboratory/pyoof/assets/39199270/320a024c-fb03-4376-8e32-d0817f4cba2c">

**Comment by tcassanelli** [comment]
Also when doing the fit are you using the same width in degrees for the beam maps?

**Comment by VicentePenaLet** [comment]
That's what the graph are, as you say, the first one is the original phase map, fixing the Zernike coefficients to be a random choice.
Then using that same Maps I made 3 fits, one using 1 frequency of 9 um, one using 2 frequencies of 7 and 9 um, and one using 3 frequencies, of 7,9 and um, this with the goal of comparing how the errors relate to the number of frequencies chosen. For each fit I'm plotting the phase map and the difference between the real Phase error, and the simulated one.

**Comment by tcassanelli** [comment]
Ah ok I understand now ... yeah seems like it works but I was maybe being too hopeful that you have worked better?
Can you plot side by side the simulated phase and then the phase of the obtained with the 3 frequency test?

**Comment by VicentePenaLet** [comment]
One reason why it may have not worked so well is that I used low resolution for the FFT so the fit would be faster. I'm repeating the same test with a better resolution and it seems like is working better. I will post the images after the algorithm finishes.

**Comment by tcassanelli** [comment]
Yeah the FFT number of point will be better for a beam map that is smaller, i.e., at high frequencies you'll need a larger FFT window, something that we should at some point, be able to return the optimum number of points for a beam map and frequency.

**Comment by VicentePenaLet** [comment]
Here are the phase differences with a higher resolution FFT. The scale of the error is a lot lower than with low resolution. reaching only 0.150 and 0.125 for the fit with one frequency and the fit with three frequencies respectively. The error also looks way flatter, with more frequencies. I think this are promising results. Adding more frequencies does in fact improve the accuracy of the fit.


<img width="423" alt="99" src="https://github.com/astronomy-laboratory/pyoof/assets/39199270/c8320a4e-5ea4-47cb-b56f-6c6b44237ec6">


<img width="423" alt="download (3)" src="https://github.com/astronomy-laboratory/pyoof/assets/39199270/7d3f5c29-6dd4-4685-a360-61751e6b85dc">

**Comment by tcassanelli** [comment]
Interesting. When doing so, did you also increase the number of data points in the simulation? i.e., did you increase the FFT size or `resolution` in the simulation and in the least-squares minimization? If that is the case then I would always expect a good result. The case that we are interested in is to set the simulation fixed and then increase the `resolution` only in the least squares minimization.
